### ISSUE TITLE
Search and menu links don't work on openhab.org/docs when directly accessing that page

### ISSUE THREAD

**Issue by Hilbrand** [openhab/website#270]
When going directly to [openhab.org/docs](http://openhab.org/docs) than searching doesn't work, and clicking on a link in the menu on the left side also doesn't work. When going to openhab.org and than clicking on docs. Then it does work and 
going directly to v2.openhab.org/docs does work too.

When going directly to the docs page the following error is given in the console (which is not given when going via the main page):

```javascript
app.8814758e.js:6 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://www.openhab.org/assets/js/app.8814758e.js:6:40632)
    at h (https://www.openhab.org/assets/js/app.8814758e.js:6:53364)
    at g (https://www.openhab.org/assets/js/app.8814758e.js:6:53101)
    at p (https://www.openhab.org/assets/js/app.8814758e.js:6:53450)
    at P (https://www.openhab.org/assets/js/app.8814758e.js:6:56788)
    at P (https://www.openhab.org/assets/js/app.8814758e.js:6:56723)
    at a.__patch__ (https://www.openhab.org/assets/js/app.8814758e.js:6:57188)
    at a.e._update (https://www.openhab.org/assets/js/app.8814758e.js:6:34424)
    at a.i (https://www.openhab.org/assets/js/app.8814758e.js:6:64504)
    at cn.get (https://www.openhab.org/assets/js/app.8814758e.js:6:26683)
```

**Comment by Confectrician** [comment]
Reproduced on Edge and Chrome.

It seems that only the docs index page is affected.
When going to other website areas everything is loaded correct.
Also navigating directly to a docs artcle loads the website correct.
